version: '2.1'
services:
  db:
    image: mariadb
    environment:
      - MYSQL_DATABASE=wiki
      - MYSQL_ROOT_PASSWORD=wiki

  mediawiki:
    build: ./mediawiki
    ports:
      - 8080:80
    depends_on:
      - db
    links:
      - db
    environment:
      - MEDIAWIKI_DB_HOST=db:3306
      - MEDIAWIKI_DB_NAME=wiki
      - MEDIAWIKI_DB_PASSWORD=wiki
